import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import Search from "./components/Search";
import DarkModeButton from "./components/DarkModeButton";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${nunito.variable} antialiased dark:bg-very-dark-blue`}
      >
        <main className="h-screen bg-very-light-gray dark:bg-very-dark-blue">
          <header className="bg-white dark:text-white px-[10%] mx-auto py-4 flex justify-between items-center dark:bg-dark-blue">
            <h1 className="font-bold">Where in the world?</h1>
            <div className="darkMode">
              <DarkModeButton></DarkModeButton>
            </div>
          </header>
          <hr />
          <Search></Search>
          {children}
        </main>
      </body>
    </html>
  );
}
